import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./common/_components/Navbar";
import Footer from "./common/_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{              
          position: 'fixed',
          top: '3%',
          zIndex: 50,
        }}>
          <Navbar/>
        </div>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
